version: '3.8'

services:
  enaj-web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: enaj_web_server
    restart: always
    ports:
      - "8081:80"
    environment:
      - TZ=America/Fortaleza
    networks:
      - enaj_network

networks:
  enaj_network:
    driver: bridge